global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets:
          - "redis:6379"
          - "db:3306"
          - "wordpress:80"
          - "zabbix-server:10051"
